Update patch set 8
Patch Set 8:

> Just to make sure I understand the problem correctly: By resolution
 > time you mean when the reviewer should be added? 

yes

 > I mean it sohuld be saved in the config fail as is, without expanding it. You could
 > wrte it yourself without suggestion (before this change)
 > "user/username".

yes.

The problem this change is introducing is that it make "invalid" suggestion because it suggest groups (e.g. ldap/somegroup, user/someuser) that it wont be able to resolve when time to for reviewers to be added. Example of an error in the logs:

Cannot resolve reviewer: ldap/contrib-adm
com.google.gerrit.extensions.restapi.UnprocessableEntityException: External Group Not Allowed: ldap/contrib-adm
	at com.google.gerrit.server.group.GroupsCollection.parseInternal(GroupsCollection.java:134)
	at com.googlesource.gerrit.plugins.reviewers.ChangeEventListener.toAccounts(ChangeEventListener.java:252)
	at com.googlesource.gerrit.plugins.reviewers.ChangeEventListener.onEvent(ChangeEventListener.java:152)
	at com.google.gerrit.common.ChangeHookRunner.fireEventForUnrestrictedListeners(ChangeHookRunner.java:742)
	at com.google.gerrit.common.ChangeHookRunner.fireEvent(ChangeHookRunner.java:754)
	at com.google.gerrit.common.ChangeHookRunner.doPatchsetCreatedHook(ChangeHookRunner.java:398)
	at com.google.gerrit.server.change.ChangeInserter.postUpdate(ChangeInserter.java:301)
	at com.google.gerrit.server.git.BatchUpdate.executePostOps(BatchUpdate.java:386)
	at com.google.gerrit.server.git.BatchUpdate.execute(BatchUpdate.java:301)
	at com.google.gerrit.server.git.ReceiveCommits$CreateRequest.insertChange(ReceiveCommits.java:1813)
	at com.google.gerrit.server.git.ReceiveCommits$CreateRequest.access$0(ReceiveCommits.java:1780)
	at com.google.gerrit.server.git.ReceiveCommits$CreateRequest$1.call(ReceiveCommits.java:1765)
	at com.google.gerrit.server.git.ReceiveCommits$CreateRequest$1.call(ReceiveCommits.java:1)
	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:96)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:61)
	at com.google.gerrit.server.git.ReceiveCommits$CreateRequest.insertChange(ReceiveCommits.java:1759)
	at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:836)
	at com.google.gerrit.server.git.ReceiveCommits.processCommands(ReceiveCommits.java:618)
	at com.google.gerrit.server.git.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at com.google.gerrit.server.util.RequestScopePropagator$5.call(RequestScopePropagator.java:222)
	at com.google.gerrit.server.util.RequestScopePropagator$4.call(RequestScopePropagator.java:201)
	at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator$1.call(ThreadLocalRequestScopePropagator.java:55)
	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:98)
	at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Patch-set: 8