Update patch set 1
Patch Set 1: Verified-1

I fail to verify this commit as well, in standalone build mode:

  ERROR: Skipping 'reviewers': error loading package '': Unable to load file '//tools/bzl:genrule2.bzl': file doesn't exist

I suspect, that this CL: [1], that implements PG UI for this plugin, broke standalone build mode.

* [1] https://gerrit-review.googlesource.com/c/plugins/reviewers/+/224402

Patch-set: 1
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1